import { AppProps } from '../node_modules/next/app';
import '../styles/globals.css';
import Head from '../node_modules/next/head';
import React from 'react';

function MyApp({ Component, pageProps, router }: AppProps): JSX.Element {
	return (
		<>
			<Head>
				<title>React-NextJS</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					href='https://fonts.googleapis.com/css2?family=Bigelow+Rules&family=Noto+Sans:wght@300;400;500;600;700&display=swap'
					rel='stylesheet'
				/>
				<meta
					property='og:url'
					content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}
				/>
				<meta
					property='og:local'
					content='ru_RU'
				/>
			</Head>
			<Component {...pageProps} />
		</>
	);
}

export default MyApp;
