import { AppProps } from '../node_modules/next/app';
import '../styles/globals.css';
import Head from '../node_modules/next/head';
import React from 'react';
import ym from 'react-yandex-metrika';
import { YMInitializer } from 'react-yandex-metrika';

function MyApp({ Component, pageProps, router }: AppProps): JSX.Element {
	router.events.on('routeChangeComplete', (url: string) => {
		if (typeof window !== 'undefined') {
			ym('hit', url);
		}
	});
	return (
		<>
			<Head>
				<title>React-NextJS</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://mc.yandex.ru' />
				<link
					href='https://fonts.googleapis.com/css2?family=Bigelow+Rules&family=Noto+Sans:wght@300;400;500;600;700&display=swap'
					rel='stylesheet'
				/>
				<meta
					property='og:url'
					content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}
				/>
				<meta property='og:local' content='ru_RU' />
			</Head>
			<YMInitializer 
				accounts={[]} 
				options={{ webvisor: true, defer: true }} 
			/>
			<Component {...pageProps} />
		</>
	);
}

export default MyApp;
